### ISSUE TITLE
Packages get installed from PyPI even if extra-index-url is specified 

### ISSUE THREAD

**Issue by sh1ng** [h2oai/py-repo#2]
https://pip.pypa.io/en/stable/reference/pip_install/#finding-packages

**Comment by st-pasha** [comment]
If you add parameter `--no-index`, then PyPI will be excluded from the list of the repositories that are searched.

Still, this repo is just a "simple python repository". It can provide to pip the list of hosted packages, but it cannot affect pip's choice of what to actually install.
